[project]
name = "data-report"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fredapi>=0.5.2",
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
]
