name: CI

on:
  push:
    branches: [ main, dev, feature/** ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install --upgrade pip
      - run: pip install .[dev]         # pulls pytest
      - run: pytest -q
